SUPABASE_URL = "https://nljwjchmjocopwamhouj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sandqY2htam9jb3B3YW1ob3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1NTE2NDEsImV4cCI6MjEwMzEyNzY0MX0.e55vhuMHUWkSuXo7iz2g-Y0NlmVglGq0Ep0C_siaI90"
